### ISSUE TITLE
Access to recorded data by USB

### ISSUE THREAD

**Issue by ghost** [STMicroelectronics/fp-sns-datalog2#20]
Hi,

We use the STWIN.box in many configurations to analyze vibrations in order to implement predictive maintenance on our systems. The STWIN.box is great for self-sufficient battery operation in a mobile environment.

It would be nice if the SD card didn't have to be removed to read the data afterwards. An alternative way of accessing the files on the card via USB, as on an external disk, would be a very welcome feature.

Anyway, you did a great job!

Kind regards
Ludwig

**Comment by pradolis** [comment]
Hello @Ferag-AG 
Thanks for your feedbacks. 
We are really appreciating the technical hints you shared with us.
We could increase the quality of our tool also thanks to your advises.

The feature you are requesting is not planned, but I can share internally your request.
In the meantime, are you aware of the possibility to read data via FTP?
This feature is available for STWIN.box only (it is the only supported board mounting a Wi-Fi module).
Have a look at chapter 2.3 FTP Data Retrieving over Wi-Fi ([link](https://www.st.com/resource/en/user_manual/um3106-getting-started-with-the-stm32cube-function-pack-for-high-speed-datalogging-and-ultrasound-processing-stmicroelectronics.pdf)).


Best regards
Simone

**Comment by ghost** [comment]
Hi @pradolis 

I've already tried WiFi / FTP twice without success. The STWIN.box won't connect to WiFi and almost every second time the FW (Datalog2 V2.2.0) crashes.

Best regards
Ludwig

**Comment by pradolis** [comment]
Hello @Ferag-AG 
have you double checked with v2.3.0?

Best regards,
Simone

**Comment by ghost** [comment]
Hi @pradolis 

No I don't have try v2.3.0, is there any relevant changes to WiFi?

**Comment by pradolis** [comment]
I fixed a corner case where, by fault, the SD card operative system were closed before opening the FTP. This caused the firmware to get stuck.

**Comment by ghost** [comment]
It sounds good, so I will have a try next week and give you feedback.

**Comment by ghost** [comment]
Hi @pradolis

Unfortunately, version 2.3.0 still doesn't work. Now the FW of the STWIN-box doesn't crash immediately after giving the WiFi crendential the ST BLE Sensor app, but a few seconds later. So at the moment it's still not possible to access to offline recorded data without removing the SD card.

Best regards
Ludwig

**Comment by pradolis** [comment]
Let me close the issue. Different newer firmware versions have already pushed in the past months, with no further news on the topic (here or on other channels from other customers).
FYI: a similar topic has been addressed on community.st.com, solving an issue on iOS BLESensor application side. As for now, latest FW + both Android either iOS BLESensor application seems working properly
